import {games} from './catalog.js';
import {createGame,clamp} from './engine.js';
import {render} from './render.js';
import {createPlatform} from './platform.js';
const root=document.querySelector('#app');
const standalone=!!window.GAME_ID;
let active=null,raf=0,last=0,playing=false,userPaused=false,hostPaused=false,keys=new Set(),pointers=new Map(),platform,status='';
platform=createPlatform({onPause(){hostPaused=true;stop();clearInput();},onResume(){hostPaused=false;last=0;resize();if(playing&&!userPaused)schedule();},onStatus(message){status=message;const el=document.querySelector('.save-status');if(el&&!hostPaused)el.textContent=message;}});
platform.firstFrame();
await platform.init();
if(!platform.youtube)document.addEventListener('visibilitychange',()=>{if(document.hidden){hostPaused=true;stop();clearInput();}else{hostPaused=false;last=0;if(playing&&!userPaused)schedule();}});
function stop(){cancelAnimationFrame(raf);raf=0;}
function schedule(){if(!raf&&!hostPaused)raf=requestAnimationFrame(frame);}
function clearInput(){keys.clear();pointers.clear();if(active){active.action('left',false);active.action('right',false);active.action('main',false);}}
function frame(time){raf=0;if(!active||!playing||hostPaused||userPaused)return;const dt=last?Math.min((time-last)/1000,.1):0;last=time;
 if(keys.has('ArrowLeft')||keys.has('a'))active.aim(active.s.target-320*dt);
 if(keys.has('ArrowRight')||keys.has('d'))active.aim(active.s.target+320*dt);
 // Small physics substeps prevent tunneling after a delayed animation frame.
 let remaining=dt;while(remaining>0){const step=Math.min(remaining,1/120);active.update(step);remaining-=step;}
 draw();if(active.s.done){playing=false;platform.record(active.s.id,active.s.score);showOverlay('ROUND COMPLETE',active.s.message,`You scored ${active.s.score}. ${active.s.id==='tennis'?`Final points: ${active.s.round}–${active.s.enemy}. `:''}Best: ${Math.max(platform.best(active.s.id),active.s.score)}.`, 'Play again',start);}else schedule();
}
function draw(){if(hostPaused)return;const canvas=document.querySelector('#game');if(!canvas||!active)return;const ctx=canvas.getContext('2d');ctx.setTransform(canvas.width/400,0,0,canvas.height/600,0,0);render(ctx,active.s);
 document.querySelector('#score').textContent=active.s.score;
 document.querySelector('#best').textContent=platform.best(active.s.id);
 const s=active.s;document.querySelector('#round-label').textContent=s.id==='soccer'?'SHOTS LEFT':s.id==='tennis'?'POINTS':s.id==='pinball'?'BALLS':s.id==='moto'?'DISTANCE':s.id==='formula'?'LAP':'TIME LEFT';
 document.querySelector('#round').textContent=s.id==='soccer'?s.shots:s.id==='tennis'?`${s.round} : ${s.enemy}`:s.id==='pinball'?s.lives:s.id==='moto'?`${(s.distance/1000).toFixed(1)} km`:s.id==='formula'?`${Math.min(3,s.round+1)} / 3`:`${Math.max(0,Math.ceil(60-s.t))}s`;
 const lives=document.querySelector('#lives');lives.textContent=['soccer','tennis'].includes(s.id)?'':`${s.lives} ${s.id==='pinball'?'balls':'lives'}`;
}
function showOverlay(kicker,title,body,button,callback){const overlay=document.querySelector('#overlay');overlay.classList.remove('hidden');overlay.innerHTML=`<div class="modal"><span class="eyebrow" style="justify-content:center">${kicker}</span><h2>${title}</h2><p>${body}</p><button class="play" id="begin">${button}</button></div>`;document.querySelector('#begin').onclick=()=>{if(!hostPaused)callback();};}
function start(){active=createGame(active.s.id);playing=true;userPaused=false;last=0;clearInput();document.querySelector('#overlay').classList.add('hidden');document.querySelector('#pause').textContent='Pause';draw();schedule();}
function pause(){if(!active||!playing||hostPaused)return;userPaused=!userPaused;clearInput();stop();if(userPaused){document.querySelector('#pause').textContent='Resume';showOverlay('TAKE A BREATHER','Paused','Your round is right here when you’re ready.','Resume',pause);}else{document.querySelector('#pause').textContent='Pause';document.querySelector('#overlay').classList.add('hidden');last=0;schedule();}}
function resize(){if(!active||hostPaused)return;const canvas=document.querySelector('#game'),wrap=document.querySelector('.stage-wrap');const r=wrap.getBoundingClientRect(),scale=Math.min(r.width/400,r.height/600);canvas.style.width=`${400*scale}px`;canvas.style.height=`${600*scale}px`;const dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(400*scale*dpr);canvas.height=Math.round(600*scale*dpr);draw();}
function openGame(id){stop();playing=false;clearInput();const info=games.find(g=>g.id===id);if(!info){gallery();return;}active=createGame(id);document.title=`${info.title} · Pocket Sports`;
 root.innerHTML=`<main class="game-shell"><div class="game-bar">${standalone?'':'<button class="soft" id="back" aria-label="Back to collection">←</button>'}<h1>${info.title}</h1><span id="lives" class="touch"></span><button class="soft" id="pause">Pause</button></div><div class="hud"><span>SCORE<strong id="score">0</strong></span><span id="round-hud"><span id="round-label">ROUND</span><strong id="round">0</strong></span><span>PERSONAL BEST<strong id="best">0</strong></span></div><div class="stage-wrap"><canvas class="stage" id="game" width="400" height="600" aria-label="${info.title} playing field. ${info.controls}" tabindex="0"></canvas><div class="overlay" id="overlay"></div></div><div class="controls">${id==='pinball'?'<button class="soft" data-action="left">◀ FLIP</button><button class="soft" data-action="launch">LAUNCH</button><button class="soft" data-action="right">FLIP ▶</button>':info.action.map(label=>`<button class="soft" data-action="main">${label}</button>`).join('')}</div><p class="hint">${info.hint}</p><p class="save-status" aria-live="polite">${status}</p></main>`;
 document.querySelector('#back')?.addEventListener('click',()=>{location.hash='';});document.querySelector('#pause').onclick=pause;
 const canvas=document.querySelector('#game');function position(e){const r=canvas.getBoundingClientRect();return clamp((e.clientX-r.left)/r.width*400,0,400);}
 canvas.addEventListener('pointerdown',e=>{if(!playing||userPaused||hostPaused)return;e.preventDefault();canvas.setPointerCapture(e.pointerId);const x=position(e);pointers.set(e.pointerId,x<200?'left':'right');active.aim(x);if(id==='pinball')active.action(pointers.get(e.pointerId),true);});
 canvas.addEventListener('pointermove',e=>{if(pointers.has(e.pointerId)&&playing&&!userPaused&&!hostPaused)active.aim(position(e));});
 function release(e,cancel=false){if(!pointers.has(e.pointerId))return;if(id==='pinball')active.action(pointers.get(e.pointerId),false);else if(id==='soccer'&&!cancel&&playing&&!userPaused&&!hostPaused)active.action();pointers.delete(e.pointerId);}
 canvas.addEventListener('pointerup',e=>release(e));canvas.addEventListener('pointercancel',e=>release(e,true));canvas.addEventListener('lostpointercapture',e=>release(e,true));
 for(const b of document.querySelectorAll('[data-action]')){const kind=b.dataset.action;b.addEventListener('pointerdown',e=>{if(!playing||userPaused||hostPaused)return;e.preventDefault();b.setPointerCapture(e.pointerId);active.action(kind,true);});for(const event of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(event,()=>active.action(kind,false));b.addEventListener('click',e=>{if(e.detail===0&&playing&&!userPaused&&!hostPaused){active.action(kind,true);setTimeout(()=>active?.action(kind,false),120);}});}
 resize();showOverlay(info.sport.toUpperCase(),info.title,info.controls,'Let’s play',start);
}
function gallery(filter='All games'){stop();active=null;playing=false;document.title='Pocket Sports — The arcade collection';const visible=games.filter(g=>filter==='All games'||g.group===filter);
 root.innerHTML=`<div class="shell"><header><div class="brand"><span class="brand-mark">↗</span> pocket sports</div><span>THE ARCADE COLLECTION / 01</span></header><section class="hero"><div><div class="eyebrow"><i class="dot"></i> Small screen. Big game.</div><h1>Your next<br>five-minute <em>rivalry.</em></h1></div><div><p class="intro">Seven little games. A whole lot of “one more go”. Pick your sport, chase your best, and play with just a thumb.</p><div class="stats"><span><strong>07</strong>original games</span><span><strong>1–2</strong>finger controls</span><span><strong>Zero</strong>downloads</span></div></div></section><div class="toolbar"><nav class="filters" aria-label="Filter games">${['All games','Ball sports','Racing','Arcade'].map(f=>`<button class="chip ${filter===f?'active':''}" aria-pressed="${filter===f}" data-filter="${f}">${f}</button>`).join('')}</nav><span class="count">${String(visible.length).padStart(2,'0')} GAMES · READY WHEN YOU ARE</span></div><section class="grid" aria-label="Game collection">${visible.map((g,i)=>`<article class="card ${filter==='All games'&&i===6?'feature':''}"><canvas class="art" width="620" height="400" data-preview="${g.id}" aria-label="${g.title} gameplay preview"></canvas><div class="card-info"><div class="card-top"><span class="category">${g.sport}</span><span class="num">${String(games.indexOf(g)+1).padStart(2,'0')} / 07</span></div><h2>${g.title}</h2><p>${g.pitch}</p><div class="card-foot"><span class="touch">${g.id==='pinball'?'◉ Two thumbs':'◉ One thumb'} · ${g.duration}</span><button class="play" data-game="${g.id}" aria-label="Play ${g.title}">Play now ↗</button></div></div></article>`).join('')}</section><div class="collection-note"><span>Made for the small screen. Just as fun on a big one.</span><span>Touch, mouse & keyboard welcome.</span></div><footer><span>POCKET SPORTS © ${new Date().getFullYear()}</span><span>Independent arcade collection · Playable pitch builds</span></footer></div>`;
 for(const b of document.querySelectorAll('[data-filter]'))b.onclick=()=>gallery(b.dataset.filter);
 for(const b of document.querySelectorAll('[data-game]'))b.onclick=()=>{location.hash=b.dataset.game;};
 for(const canvas of document.querySelectorAll('[data-preview]')){const s=createGame(canvas.dataset.preview).s;s.keeper=245;s.aim=130;s.x=210;s.ai=160;s.distance=230;s.road=200;s.objects=[{x:110,y:150,type:'enemy'},{x:285,y:330,type:'enemy'},{x:195,y:220,type:'coin'}];if(s.id==='pinball')s.ball={x:265,y:340};const temp=document.createElement('canvas');temp.width=400;temp.height=600;render(temp.getContext('2d'),s,{preview:true});const c=canvas.getContext('2d');c.fillStyle=games.find(g=>g.id===s.id).color;c.fillRect(0,0,620,400);c.save();c.translate(310,200);c.rotate(-.13);c.shadowColor='#0005';c.shadowBlur=28;c.drawImage(temp,-145,-217,290,435);c.restore();}
}
window.addEventListener('resize',resize);
window.addEventListener('blur',clearInput);
window.addEventListener('keydown',e=>{if(hostPaused)return;if(e.key==='Escape'){if(playing)pause();return;}if(!active||!playing||userPaused)return;if(['ArrowLeft','ArrowRight',' ','a','d'].includes(e.key))e.preventDefault();if(e.repeat)return;keys.add(e.key);if(active.s.id==='pinball'){if(e.key==='ArrowLeft'||e.key==='a')active.action('left',true);if(e.key==='ArrowRight'||e.key==='d')active.action('right',true);if(e.key===' ')active.action('launch');}else if(e.key===' ')active.action();});
window.addEventListener('keyup',e=>{keys.delete(e.key);if(!active||hostPaused)return;if(e.key==='ArrowLeft'||e.key==='a')active.action('left',false);if(e.key==='ArrowRight'||e.key==='d')active.action('right',false);if(e.key===' ')active.action('main',false);});
function route(){if(hostPaused)return;const id=window.GAME_ID||location.hash.slice(1);if(id)openGame(id);else gallery();}
window.addEventListener('hashchange',()=>{if(!standalone)route();});route();platform.ready();
